name: Create Release and Update Repository

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    uses: drarkomonn/DalamudPluginRepo/.github/workflows/reusable_create_release.yml@main
    with:
      internal_name: NoClippy
      solution_name: NoClippy
      build_configuration: Release
      personal_plugin_repo: drarkomonn/DalamudPluginRepo
      personal_plugin_repo_branch: master
    secrets: inherit
